project:
  type: r3-theme
  pre-render:
     quarto render slides/*.qmd

book:
  title: "Introduction to GitHub"
  author:
    - Signe Kirk Brødbæk
    - Luke W. Johnston
  date: last-modified
  repo-url: https://github.com/rostools/github-intro
  site-url: https://github-intro.rostools.org
  chapters:
    - index.qmd
    - part: "Overview"
      chapters:
      - overview/syllabus.qmd
      - overview/is-this-for-you.qmd
      - overview/learning-design.qmd
      - overview/schedule.qmd
    - part: "Pre-workshop"
      chapters:
        - pre-workshop/overview.qmd
        - pre-workshop/code-of-conduct.qmd
        - pre-workshop/git-and-github.qmd
        - pre-workshop/github-account.qmd
        - pre-workshop/survey.qmd
    - part: "Sessions"
      chapters:
      - sessions/introduction.qmd
      - sessions/basics.qmd
      - sessions/working-with-files.qmd
      - sessions/using-issues.qmd
      - sessions/conclusion.qmd
  appendices:
    - appendix/for-teachers.qmd
  page-footer:
    center:
      - text: "License: CC BY 4.0 {{< fa brands creative-commons >}} {{< fa brands creative-commons-by >}}"
        href: LICENSE.html
      - text: "Code of Conduct"
        href: "https://guides.rostools.org/conduct.html"

format:
  r3-theme-html: default

editor:
  markdown:
    wrap: 72
    canonical: true
