# Overview of pre-workshop tasks {#sec-pre-workshop}

In order to participate in this workshop, you must complete everything
in this section and finish with **completing the
[survey](/pre-workshop/pre-survey.qmd)** at the end. These tasks are
designed to make it easier for everyone to start the workshop with
everything set up and a shared foundation to build on.

Depending on your skills and knowledge, these tasks could take between
**1-2 hrs to finish**, so we suggest planning some time to complete
them. While many of the tasks are mostly readings, they are important in
making sure you get the most out of the workshop.

## Summary of tasks

Here's a quick overview of the tasks you need to do. Specific details
about them are found as you work through the tasks.

If you haven't already, go through the workshop overview section,
including the [Syllabus](/overview/syllabus.qmd), [Is this for
you?](/overview/is-it-for-you.qmd), and [Learning
design](/overview/learning-design.qmd) to get an overview of what this
workshop contains and the learning design behind the workshop material.

After that, please go through the the pre-workshop tasks to help build a
shared foundation to build on when the workshop starts. This includes:

1.  Reading the [Code of conduct](/pre-workshop/code-of-conduct.qmd)
2.  Reading the section [Version control with Git and
    GitHub](/pre-workshop/git-and-github.qmd),
3.  Creating a [GitHub user account](/pre-workshop/github-account.qmd).
4.  Filling out the pre-workshop [survey](/pre-workshop/pre-survey.qmd)
    at the end.

::: callout-tip
You will be taken through the pre-workshop tasks in order by clicking
the arrow at the bottom of each page.
:::
