# Syllabus {#sec-syllabus}

Over the last few decades, the way we do research has substantially
changed as the internet and, especially, digital technologies and social
media have become more embedded in even the more traditional and
conservative parts of our society. This has impacted research in
multiple ways and has placed a greater need, expectation, and/or
pressure on a wide and diverse range of things. Some of these needs
include, in in no particular order:

1.  Formally disseminate more types of new or existing knowledge and
    scientific output
2.  Informally sharing information, discussions, or ideas more
    frequently and more rapidly
3.  Collaborate more with others across regions and timezones
4.  Be more open and transparent about the whole research process
5.  Network and connect with others in the research community and, at
    least in health, those who participate or want to participate in
    research using a wider variety of tools and platforms

While academia and research pursue expanding the boundaries of our
collective knowledge, we also paradoxically are very slow to adapt to
and adopt changes, especially technological. But the needs listed above
are now so great that we must embrace these tools tools to effectively
fulfil those needs.

This workshop introduces you to one such tool and way of working and
communicating that is very common in industry and becoming more common
in academia: GitHub. While GitHub can fulfil the needs above and much
more, for this workshop we will mainly focus on the transparency and
sharing aspects, rather than the collaboration aspects.

This workshop lasts 3 hours and is split into the following sessions,
listed in the schedule in @sec-schedule, which will be covered in order:

-   Introduction to the workshop in [session @sec-introduction]
-   The basics of GitHub and Git in [session @sec-basics]
-   Working with files on GitHub in [session @sec-working-with-files]
-   Making and using GitHub Issues in [session @sec-using-issues]
-   Concluding remarks in [session @sec-conclusion]

## Learning outcome and objectives

The aim of this workshop is to enable you to:

-   Explain in simple terms what GitHub does and navigate GitHub to work
    with files and GitHub Issues.

Broken down into specific objectives, the workshop
will enable you to do the following, by session:

**The basics of GitHub and Git** ([session @sec-basics])

{{< include /includes/objectives/_basics.qmd >}}

**Working with files on GitHub** ([session @sec-working-with-files])

{{< include /includes/objectives/_working-with-files.qmd >}}

**Making and using GitHub Issues** ([session @sec-using-issues])

{{< include /includes/objectives/_using-issues.qmd >}}

Tangibly, during the workshop we will:

-   Create your own project on GitHub (known as a *repository*)
-   Create and edit text files and folders on GitHub.
-   Create GitHub Issues and comment on them.

We will not go into using GitHub for collaboration as that is beyond the
scope of this workshop.

## Is this for you? {#sec-is-it-for-you}

To help manage expectations and develop the material for this workshop,
we make a few possible assumptions about *who you are* as a participant
in the workshop, such as one or more of the following:

-   You want a gentle introduction to what GitHub is and how to use it.
-   You mostly work alone or maybe irregularly with someone else on your
    project.
-   You write text in documents as a main activity of your work.
-   You are able to and are comfortable enough with only working on
    files through a web browser interface (like GitHub's interface).

While we have these assumptions to help focus the content of the
workshop, if you have an interest in the workshop but don't fit any of
the assumptions, *you are still welcome to attend*! We welcome everyone
until capacity has been reached.

In addition to the assumptions, we also have a fairly focused scope for
teaching and expectations for learning. So this may also help you decide
if this workshop is for you.

-   We will only interact with GitHub from the website and from a web
    browser.
-   We will only write *text*, there will be no code or programming.
-   While we will write in a `.md` Markdown file, we will not write or
    cover Markdown syntax.
-   We will not go over too many details of Git (a software that GitHub
    relies on).
