# Schedule {#sec-schedule}

This 3-hour workshop is structured as a participatory live-coding session
interspersed with a few hands-on exercises, reading tasks, and discussion
activities. The general schedule outline is shown in the below table. This is
not a fixed schedule of the timings of each session --- some may be shorter and
others may be longer. Instead, it is meant to be an approximate guide and
overview.

| Minutes | Session topic |
|:-----------------------------------|:-----------------------------------|
|  | {{< fa mug-hot >}} Arrival, coffee and tea |
| 15 | {{< fa person-chalkboard >}} [Introduction to the workshop](/sessions/introduction.qmd) |
| 45 | {{< fa person-chalkboard >}} [The basics of GitHub and Git](/sessions/basics.qmd) |
| 5 | {{< fa mug-hot >}} Short break |
| 50 | {{< fa laptop-code >}} [Working with files on GitHub](/sessions/working-with-files.qmd) |
| 5 | {{< fa mug-hot >}} Short break |
| 30 | {{< fa laptop-code >}} [Making and using GitHub Issues](/sessions/using-issues.qmd) |
| 10 | {{< fa person-chalkboard >}} [Concluding remarks](/sessions/conclusion.qmd) |
| 10 | {{< fa comment-dots >}} [Short end of workshop survey]({{< meta surveys.feedback >}}) |
