# Syllabus {#sec-syllabus}

Over the last few decades, the way we do research has substantially
changed as digital technologies and social media have become more
embedded in even the more traditional and conservative parts of our
society. This shift has affected research in multiple ways and has
increased the need, expectation, and/or pressure on various aspects.
These needs include, in no particular order, being able to:

1.  Formally disseminate more types of new or existing knowledge and
    scientific output.
2.  Informally share information, discussions, or ideas regularly and
    quickly.
3.  Collaborate more across regions and timezones.
4.  Be more open and transparent about the whole research process.
5.  Network and connect with others in the research community and, at
    least in health, those who participate or want to participate in
    research using a wider variety of tools and platforms.

While academia and research seek to expand the boundaries of our
collective knowledge, we also paradoxically are very slow to adapt to
and adopt changes, especially technological ones. But the needs listed
above are now so great that we must embrace new tools to effectively
fulfil those needs.

This workshop introduces you to one such tool widely used for working
and communicating in industry and increasingly in academia: GitHub.
While GitHub can fulfil the needs above (and much more) we will focus on
using GitHub to enhance the transparency and sharing aspects for this
workshop (4. in the list above), rather than the collaboration aspects.

During this workshop, we'll be just scratching the surface of what Git
and GitHub can do, focusing on the essentials to help you get started.
We'll use GitHub's web interface as a learning tool, giving you a simple
way to explore and practice the basics of working with files on GitHub.
While this approach is less powerful than working directly with Git, it
serves as a gentle introduction to the key concepts and workflows. Our
goal is that what you are introduced to in this workshop will provide a
solid foundation, preparing you to build toward more open, transparent,
and advanced practices with GitHub.

This workshop lasts 3 hours and is split into the following sessions,
listed in the [schedule](/overview/schedule.qmd):

-   [Introduction to the workshop](/sessions/introduction.qmd)
-   [The basics of Git and GitHub](/sessions/basics.qmd)
-   [Creating a repository on GitHub](/sessions/create-repo.qmd)
-   [Working with files on GitHub](/sessions/working-with-files.qmd)
-   [Making and using GitHub Issues](/sessions/using-issues.qmd)
-   [Concluding remarks](/sessions/conclusion.qmd)

## Learning outcome and objectives

The overall aim of this workshop is to enable you to:

{{< include /includes/objectives/_overall.qmd >}}

Broken down into specific objectives for each session, we've designed
the workshop to enable you to do the following:

[**The basics of Git and GitHub**](/sessions/basics.qmd)

{{< include /includes/objectives/_basics.qmd >}}

[**Creating a repository on GitHub**](/sessions/create-repo.qmd)

{{< include /includes/objectives/_create-repo.qmd >}}

[**Working with files on GitHub**](/sessions/working-with-files.qmd)

{{< include /includes/objectives/_working-with-files.qmd >}}

[**Making and using GitHub Issues**](/sessions/using-issues.qmd)

{{< include /includes/objectives/_using-issues.qmd >}}

Tangibly, during the workshop you will:

-   Create your own project on GitHub (known as a *repository*)
-   Create and edit text files and folders on GitHub.
-   Create GitHub Issues and comment on them.

We will not go into using GitHub for collaboration as that is beyond the
scope of this workshop.
